### PyTorch Resources:

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
!nvidia-smi

Mon Oct  2 18:58:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## introduction to Tensors

### creating tensors

In [2]:
## scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [8,9,7]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [8, 9, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 7]])

In [ ]:
TENSOR[1]

IndexError: ignored

In [ ]:
TENSOR1 = torch.tensor([[TENSOR1[[[1,2,3],
                           [4,5,6]]]]])

In [ ]:
TENSOR1

tensor([[[[[1, 2, 3],
           [4, 5, 6]]]]])

In [ ]:
TENSOR1.ndim

5

In [ ]:
TENSOR1[0]

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

### Random Tensors

These are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# create random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7247, 0.4794, 0.2695, 0.4353],
        [0.7988, 0.0370, 0.0953, 0.1901],
        [0.9124, 0.8765, 0.7723, 0.7335]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor1 = torch.rand(1,10,10)
random_tensor1

tensor([[[0.0403, 0.3889, 0.5450, 0.3576, 0.9192, 0.1630, 0.1388, 0.3422,
          0.9426, 0.1863],
         [0.7083, 0.1918, 0.8932, 0.0036, 0.4094, 0.5317, 0.0135, 0.2733,
          0.5731, 0.1539],
         [0.5636, 0.6244, 0.9139, 0.2388, 0.4797, 0.5390, 0.4076, 0.7239,
          0.0279, 0.4136],
         [0.2486, 0.2414, 0.4215, 0.4750, 0.6674, 0.7114, 0.3875, 0.8864,
          0.1923, 0.0186],
         [0.9550, 0.1019, 0.1601, 0.6003, 0.4094, 0.3748, 0.1657, 0.7053,
          0.6746, 0.2974],
         [0.4548, 0.5679, 0.5474, 0.3305, 0.9166, 0.8254, 0.6610, 0.0170,
          0.5522, 0.4360],
         [0.1917, 0.9691, 0.1902, 0.4075, 0.6437, 0.2225, 0.3537, 0.0283,
          0.2156, 0.9823],
         [0.2443, 0.1440, 0.1419, 0.9204, 0.5733, 0.5602, 0.1206, 0.7056,
          0.2213, 0.1198],
         [0.1464, 0.8954, 0.8811, 0.8136, 0.4223, 0.7056, 0.4526, 0.3643,
          0.3688, 0.6329],
         [0.5123, 0.1258, 0.1532, 0.6827, 0.0429, 0.4352, 0.5010, 0.6482,
          0.5275,

In [ ]:
random_tensor1.ndim

3

In [ ]:
### create a random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels

In [ ]:

random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

### Zeroes and Ones

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1,11)

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=0,end=1000,step=77)

one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# creating tensors-like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

In [ ]:
# float32 tensors

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [ ]:
# Find out details about it

some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9408, 0.5675, 0.4652, 0.7373],
        [0.9816, 0.6572, 0.5958, 0.2378],
        [0.0611, 0.2761, 0.6461, 0.0038]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (Tensor Operations)

Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10 #add

tensor([11, 12, 13])

In [ ]:
tensor - 10 #subtract

tensor([-9, -8, -7])

In [ ]:
tensor * 10 #multiply

tensor([10, 20, 30])

In [ ]:
# pytorch inbuilt functions

torch.mul(tensor,100)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,100)

tensor([101, 102, 103])

### Matrix Multiplication

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

- (3, 2) @ (3, 2) won't work
- (2, 3) @ (3, 2) will work
- (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)

**Note: "@" in Python is the symbol for matrix multiplication.**

PyTorch Matrix Multiplication Docs:
https://pytorch.org/docs/stable/generated/torch.matmul.html

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 3.18 ms, sys: 0 ns, total: 3.18 ms
Wall time: 4.24 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 520 µs, sys: 31 µs, total: 551 µs
Wall time: 423 µs


tensor(14)

torch method is really faster than our custom code

### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [9]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [10]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5108, 1.2044, 0.4202],
        [0.6451, 1.2394, 0.6304],
        [0.2706, 0.6286, 0.2260]])


We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- `torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
- `tensor.T` - where tensor is the desired tensor to transpose.

In [11]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [12]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [13]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [14]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

visualize matrix multiplication:
http://matrixmultiplication.xyz/

### Find the min, max, mean, sum, etc. of Tensor

In [16]:
x = torch.arange(0,100,10)

In [17]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
torch.min(x)

tensor(0)

In [19]:
torch.max(x)

tensor(90)

In [20]:
torch.mean(x)

RuntimeError: ignored

In [21]:
x.dtype

torch.int64

In [24]:
x = x.type(torch.float32)

In [25]:
x.dtype

torch.float32

In [26]:
torch.mean(x)

tensor(45.)

In [27]:
torch.sum(x)

tensor(450.)

### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself
(we'll see this in a later section when using the softmax activation function).



In [28]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [30]:
tensor[8]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

- `torch.reshape(input, shape)`	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
- `Tensor.view(shape)`	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- `torch.stack(tensors, dim=0)`	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- `torch.squeeze(input)`	Squeezes input to remove all the dimenions with value 1.
- `torch.unsqueeze(input, dim)`	Returns input with a dimension value of 1 added at dim.
- `torch.permute(input, dims)`	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [41]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
# add an extra dimension
x_reshaped = x.reshape(1,7)

RuntimeError: ignored

In [50]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [44]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
#changing z changes x

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [46]:
#stack
x_stacked = torch.stack([x,x,x,x],dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [47]:
x_stacked = torch.stack([x,x,x,x],dim =1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [48]:
x_stacked = torch.stack([x,x,x,x],dim =2)
x_stacked

IndexError: ignored

In [51]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
x_reshaped.squeeze().shape

torch.Size([9])

In [54]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [57]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [58]:
#You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [59]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 102, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 102, 3])
New shape: torch.Size([3, 224, 102])


In [69]:
x_original[1,1,0]

tensor(0.9416)

In [70]:
x_permuted[1,1,0]

tensor(0.3426)

### Indexing (selecting data from tensors)
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [71]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
print(x[0][0])
print(x[0,0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [75]:
print(x[0][0][0])
print(x[0,0,0])

tensor(1)
tensor(1)


In [78]:
x[1]

IndexError: ignored

In [80]:
x[0,2,2]

tensor(9)

In [83]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimensions

x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension

x[:,1,1]

tensor([5])

In [87]:
# get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])


### Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

*start with random numbers -> tensor operations -> try to make better (again and again and again)*

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [88]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6374, 0.1902, 0.2692, 0.8619],
        [0.3339, 0.0693, 0.8093, 0.2399],
        [0.3409, 0.3270, 0.5367, 0.9034]])
tensor([[0.7576, 0.4092, 0.2260, 0.5872],
        [0.3067, 0.0335, 0.5271, 0.6509],
        [0.2627, 0.8719, 0.8853, 0.0236]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# let's make some random but reproducible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Getting PyTorch to run on GPU

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU
You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

In [5]:
some_tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(some_tensor, some_tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# move the tensor to GPU (if available)

some_tensor_on_gpu = some_tensor.to(device)
some_tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU
What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

In [7]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
some_tensor_on_gpu.numpy()

TypeError: ignored


Instead, to get a tensor back to CPU and usable with NumPy we can use `Tensor.cpu()`.

This copies the tensor to CPU memory so it's usable with CPUs.

In [8]:
tensor_back_on_cpu = some_tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])


The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [10]:
some_tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')